### ISSUE TITLE
urllib3 1.25 and below does not work with this library

### ISSUE THREAD

**Issue by 99littlebugs** [launchdarkly/python-eventsource#25]
**Describe the bug**
`urllib3` < 1.26.0 does not work with this library even though `pyproject.toml` allows `urllib3 = ">=1.22.0,<3"`

**To reproduce**
1. Use `launchdarkly-server-sdk` version 9.2.0 and `launchdarkly-eventsource` version 1.1.0, along with `urllib3` version 1.25.10
2. When trying to evaluate flags (with streaming turned on), continually get the error `Unexpected error on stream connection: __init__() got an unexpected keyword argument 'other', will retry`

**Expected behavior**
No errors and the ability to evaluate flags. 

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
`launchdarkly-server-sdk` version 9.2.0 and `launchdarkly-eventsource` version 1.1.0

**Language version, developer tools**
Python 3.8.18

**OS/platform**
N/A

**Additional context**
Tracing the errors, we've found that this library used the urllib3 retry object [here](https://github.com/launchdarkly/python-eventsource/blob/1.1.0/ld_eventsource/http.py#L67) and is passing in `other` as an argument. urllib3 doesn't support the other keyword prior to 1.26.0 ([see MR](https://github.com/urllib3/urllib3/pull/1824))

**Comment by keelerm84** [comment]
Thank you for bringing this to our attention. I have a PR up now and will let you know once a fix has been released.
